name: This is a test
favicon: null
layout_spectrum: 1
typography_spectrum: 0.39964791550301015
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00a4d7'
    - '#0a4f8e'
    - '#5484b1'
    - '#a7c0d7'
  brandStrength: 1
  lightness: 0.09596213232725859
  saturation: 0.7071708324365318
  rhythmicContrast: 0.7817753667477518
purpose: []
